server:
  port: 5000
external-api:
  key: ffb03fb1d565a5fa4479d381bd66aa6b
  base-url: api.openweathermap.org/data/2.5/forecast
  cities-resource-file-name: city.list.json
  default-days-count: 10
  initial-cities:
    city1: London
    city2: Moscow
    city3: Tokyo
  units: imperial
